"""
utils/export.py — Export LawAI responses to PDF.

Uses fpdf2 to generate a styled PDF report from a query + answer + citations.
This module is optional; if fpdf2 is not installed, app.py silently skips it.
"""

from __future__ import annotations

from datetime import datetime
from typing import List, Dict, Any


def export_response_to_pdf(
    question: str,
    answer: str,
    citations: List[Dict[str, Any]],
) -> bytes:
    """
    Generate a PDF document from a LawAI response.

    Parameters
    ----------
    question : str
        The user's original question.
    answer : str
        The LLM-generated answer.
    citations : list[dict]
        Retrieved context dicts with act_name, page_number, section, text.

    Returns
    -------
    bytes
        PDF file contents as bytes.
    """
    try:
        from fpdf import FPDF
    except ImportError as exc:
        raise ImportError(
            "fpdf2 is required for PDF export. Install with: pip install fpdf2"
        ) from exc

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Header ────────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(201, 168, 76)  # gold
    pdf.cell(0, 10, "LawAI India", ln=True, align="C")

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(130, 130, 130)
    pdf.cell(0, 6, "AI-Powered Indian Legal Research Assistant", ln=True, align="C")
    pdf.cell(
        0,
        6,
        f"Generated: {datetime.now().strftime('%d %B %Y %H:%M')}",
        ln=True,
        align="C",
    )
    pdf.ln(4)

    # Divider
    pdf.set_draw_color(201, 168, 76)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # ── Question ──────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 8, "Question", ln=True)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(60, 60, 60)
    pdf.multi_cell(0, 6, question)
    pdf.ln(4)

    # ── Answer ────────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 8, "Legal Analysis", ln=True)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    # Remove markdown bold/italic for plain PDF
    clean_answer = answer.replace("**", "").replace("*", "")
    pdf.multi_cell(0, 6, clean_answer)
    pdf.ln(6)

    # ── Citations ─────────────────────────────────────────────────────────────
    if citations:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 8, "Legal Sources", ln=True)

        for i, ctx in enumerate(citations, 1):
            score_pct = int((1 - ctx.get("score", 0)) * 100)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(150, 100, 20)
            label = (
                f"[{i}] {ctx.get('act_name','Unknown')} — "
                f"Page {ctx.get('page_number','?')}"
            )
            if ctx.get("section"):
                label += f" | Section {ctx['section']}"
            label += f" | Relevance {score_pct}%"
            pdf.cell(0, 7, label, ln=True)

            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(80, 80, 80)
            excerpt = ctx.get("text", "")[:300].replace("\n", " ")
            pdf.multi_cell(0, 5, excerpt + "…")
            pdf.ln(3)

    # ── Disclaimer ────────────────────────────────────────────────────────────
    pdf.ln(4)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(140, 140, 140)
    pdf.multi_cell(
        0,
        5,
        "DISCLAIMER: This document is generated by LawAI India for educational "
        "purposes only and does not constitute legal advice. Please consult a "
        "qualified legal professional for advice on specific legal matters.",
    )

    return bytes(pdf.output())
